googleAnalytics = "G-8HC0L8G6G8"
title: Gamers vs. Depression
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
