backend:
  name: git-gateway
  branch: main

collections:
- name: "blog"
  label: "blog"
  files: 
  fields: 
      {
        - { label: "Layout", name: "layout", widget: "hidden", default: "link.njk" }
        - { label: "Description", name: "description", widget: "text" }
        - { label: "Destination", name: "destination", widget: "text" }
      }