backend:
  name: git-gateway
  branch: master

  media_folder: "static/images/uploads"
  public_folder: "/images/uploads"

  collections:
    - name: blog
      label: "Blog"
      folder: content/blog
      create: true
      slug: "{{year}}-{{slug}}"
      fields:
  - label: "Title"
    name: "title"
    widget: "string"
    pattern: ['.{10,}', "Must have at least 20 characters"]
  - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
  - {label: "Body", name: "body", widget: "markdown"}