backend:
  name: git-gateway
  branch: main

collections:
- name: "pages",
  label: "Junctions",
  files: 
    - label: "Homepage",
      name: "homepage",
      file: "index.html"
      fields: 
        {
          - { label: "Layout", name: "layout", widget: "hidden", default: "link.njk" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Destination", name: "destination", widget: "text" }
        }